[credentials]
usernames = ["guneet"]
passwords = ["pass1234"] # use strong passwords in real apps
names = ["Guneet Singh"]


[cookie]
name = "heart_auth"
key = "a-very-secret-cookie-key"
expiry_days = 3